version: "3.9"
services:
  stress:
    build:
      context: .
    deploy:
      replicas: 1 # set here the amount of containers
    restart: always
    networks:
      - dockervlan
    env_file:
      - .env

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "10.2.10.0/23"
          ip_range: "10.2.10.0/23"
          gateway: "10.2.10.254"